#!/usr/bin/env bash
# generado inicialmente con comando
# export APPNAME=splunk-light && py2txt ~/dropbox/learning/docker.py | bash 
    
echo "building docker app image"
docker build -t splunk-light .

    
echo "Stop previous instance"
docker stop splunk-light
echo "Delete previous app image"
docker rm splunk-light
# create a deamon docker. using the same name of the app
echo "Run the server"
docker run -d --env-file .env -p 80:8080 --name splunk-light splunk-light
    
echo "To connect to the running daemon interactively using bash, type" 
echo "   docker exec -ti splunk-light /bin/bash"
