#!/usr/bin/env bash
# generado inicialmente con comando
# export APPNAME=splunk-light && py2txt ~/dropbox/learning/docker.py | bash 
# substitute this with your main script
echo "Hello world. Docker app splunk-light created and running"
